
LOG_FOLDER = "./log"

# DATA
MAX_COUNT_OF_ERROR_IMAGES = 10

# MODEL
BASE_MODEL = 'tf_efficientnet_b0_ns'

# TRAIN
RANDOM_SEED = 123
BATCH_SIZE = 256
EPOCHS = 50
TRAIN_TEST_SPLIT = 0.9
LEARNING_RATE = 0.01
SCHEDULER_LR_MULT_FACTOR = 0.5
SCHEDULER_PLATO_SIZE = 5