
LOG_FOLDER = "./log"

# DATA
MAX_COUNT_OF_ERROR_IMAGES = 15

# MODEL
BASE_MODEL = 'tf_efficientnet_b0_ns'
CLASSES_NUMBER = 10

# TRAIN
RANDOM_SEED = 123
BATCH_SIZE = 256
EPOCHS = 50
TRAIN_TEST_SPLIT = 0.9
LEARNING_RATE = 0.01
SCHEDULER_LR_MULT_FACTOR = 0.5
SCHEDULER_PLATO_SIZE = 5

# INFERENCE
INFERENCE_BATCH_SIZE = 32